# Generated by Django 2.1.2 on 2018-12-25 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ModelOfBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('img0', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('viewers', models.PositiveIntegerField(default=1)),
                ('contact_number', models.BigIntegerField(blank=True, null=True)),
                ('whatsapp_number', models.BigIntegerField(blank=True, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('is_freezed', models.BooleanField(default=False)),
                ('year_of_made', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)])),
                ('transmission', models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Tiptronic', 'Tiptronic')], max_length=120, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_is_hidden', models.BooleanField(default=False)),
                ('Kilometer', models.IntegerField(blank=True, null=True)),
                ('roof_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Convertable', 'Convertable')], max_length=120, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='SellingPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('img0', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img5', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('img6', models.ImageField(blank=True, null=True, upload_to='posts_img')),
                ('viewers', models.PositiveIntegerField(default=1)),
                ('contact_number', models.BigIntegerField(blank=True, null=True)),
                ('whatsapp_number', models.BigIntegerField(blank=True, null=True)),
                ('email_address', models.CharField(blank=True, max_length=250, null=True)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('is_freezed', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price_is_hidden', models.BooleanField(default=False)),
                ('roof_type', models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Convertable', 'Convertable')], max_length=120, null=True)),
                ('Kilometer', models.IntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Tiptronic', 'Tiptronic')], max_length=120, null=True)),
                ('year_of_made', models.IntegerField(choices=[(1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019)])),
                ('wish_to_answer', models.BooleanField(default=False)),
                ('first_owner', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Second owner', 'Second wner'), ("Don't know", "Don't know")], max_length=120, null=True)),
                ('kuwait_agent', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True)),
                ('under_warranty', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=120, null=True)),
                ('accidents', models.CharField(blank=True, choices=[('yes', 'yes'), ('No', 'No'), ("Don't know", "Don't know")], max_length=120, null=True)),
                ('repainted', models.CharField(blank=True, choices=[('yes', 'yes'), ('No', 'No'), ('General paint', 'General paint'), ('Some parts', 'Some parts')], max_length=120, null=True)),
                ('condition', models.CharField(blank=True, choices=[('Excellent', 'Excellent'), ('Very good', 'Very good'), ('Good', 'Good'), ('acceptable', 'acceptable'), ('bad', 'bad')], max_length=120, null=True)),
                ('acceptable_min_price', models.CharField(blank=True, max_length=250, null=True)),
                ('visible_defects', models.CharField(blank=True, max_length=250, null=True)),
                ('car_specs', models.TextField(blank=True, null=True)),
                ('other_comments', models.TextField(blank=True, null=True)),
                ('examination_clause', models.CharField(blank=True, choices=[('yes', 'yes'), ('No', 'No')], max_length=120, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SellingPost')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ModelOfBrand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SellingPost'),
        ),
        migrations.AddField(
            model_name='post',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ModelOfBrand'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
