# Generated by Django 2.1.2 on 2018-11-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellingbrandscategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
