# Generated by Django 2.1.2 on 2018-10-20 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181019_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingbrandscategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='api.Category'),
        ),
    ]
