# Generated by Django 2.1.2 on 2018-11-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181117_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewrs',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
