# Generated by Django 2.1.2 on 2018-11-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181124_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extra_phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
