# Generated by Django 2.1.2 on 2018-10-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181023_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], default='manual', max_length=120),
            preserve_default=False,
        ),
    ]
