# Generated by Django 2.1.2 on 2018-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_transmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=3, default=12.0, max_digits=6),
            preserve_default=False,
        ),
    ]
