# Generated by Django 2.1.2 on 2018-11-28 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_post_extra_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_freezed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
