# Generated by Django 2.1.2 on 2018-10-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Blue', 'Blue'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Red', 'Red'), ('Blue', 'Blue'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Tan', 'Tan'), ('Brown', 'Brown'), ('Grey', 'Grey')], default='White', max_length=120),
            preserve_default=False,
        ),
    ]
