# Generated by Django 2.1.2 on 2018-12-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20181130_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='price_is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='brand_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClassesOfTheBrand'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
