# Generated by Django 2.1.2 on 2018-10-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181023_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Kilometer',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback'), ('Coupe', 'Coupe'), ('Convertible', 'Convertible'), ('Pickup Truck', 'Pickup Truck'), ('Sport', 'Sport'), ('MicroCar', 'MicroCar'), ('Van', 'Van')], max_length=120, null=True),
        ),
    ]
