# Generated by Django 2.1.2 on 2018-12-11 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181211_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='brand_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ClassesOfTheBrand'),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
