# Generated by Django 2.1.2 on 2018-10-25 18:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20181023_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 10, 25, 18, 34, 11, 474443, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
